#+TITLE: ilm - minimal emacs distro
#+AUTHOR: Ildenir Barbosa
#+STARTUP: showeverything

The ILM project is a repository on GitHub that contains my personal Emacs configurations. The goal is to provide a set of customizations that can be used to enhance the user's productivity and efficiency in Emacs. These configurations include custom keyboard shortcuts, additional packages, custom themes, and other customization options that make Emacs more suitable for the user's specific needs. The project can be useful for those who want to make the most out of Emacs and turn it into a more effective tool for their daily routine.

* Usage

  Download the git repository on directory ilm

  #+BEGIN_SRC sh
	git clone https://github.com/ildenir/ilm.git ilm
	alias ilm='emacs -l ~/ilm/init.el'
  #+END_SRC

  Run emacs with new configurations

  #+BEGIN_SRC sh
	ilm arquivo
  #+END_SRC

  Or use the scripts =ilm= and =il=, to edit in graphical mode and
  console mode, respectively.

  Inserting configurations through  =.emacs=

  #+BEGIN_EXAMPLE
  git clone https://github.com/ildenir/ilm.git ilm
  cat << eof >> ~/.emacs
    (add-to-list 'load-path (expand-file-name "~/ilm"))
    (require 'ilm)
  eof
  emacs
  #+END_EXAMPLE

* Modes and Customizations

  All packages of the distro is installed on the directory `~/.ilm.d`.
  To reinstall everything, remove this directory and reexecute emacs.

* Keymap


  | Keybinding | Descricao                      |
  |------------+--------------------------------|
  | C-c w w    | Enable/Disable whitespace-mode |
  | C-c w c    | Run whitespace cleanup         |
  | <f9>       | Alternate other frame          |
  | C-x G      | Magit status                   |
  | M-y        | Helm show *kill ring* visual   |
  | C-c h      | Helm command prefix            |
  | M-<left>   | Scroll window one line up      |
  | M-<right>  | Scroll window one line down    |
  | C-c l      | Org mode store link            |
  | C-c a      | Org mode agenda                |

* Configuracoes
- Enable automatic whitespace cleanup when file is saved.

*  Distros mais completas
 - [[https://github.com/bbatsov/prelude][Emacs Prelude]] : distribuicao para Emacs 24
 - [[https://github.com/syl20bnr/spacemacs][Spacemacs]]  : vim based ux distro

* Referencia
- [[http:tuhdo.github.io/helm-intro.html][A Package in a league of its own]]
